# Generated by Django 4.1.2 on 2022-11-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_04', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
