# Generated by Django 4.1.2 on 2022-11-05 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NullBlankDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blanknull', models.IntegerField(blank=True, null=True)),
                ('default', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45)),
                ('code_name', models.CharField(max_length=30, unique=True)),
                ('deadline', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=50)),
                ('years_of_exp', models.PositiveIntegerField()),
                ('review', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('works_full_time', models.BooleanField()),
                ('photo', models.URLField()),
                ('start_date', models.DateField()),
                ('birth_date', models.DateField()),
                ('level', models.CharField(choices=[('Junior', 'Junior'), ('Regular', 'Regular'), ('Senior', 'Senior')], max_length=7, verbose_name='Seniority Level')),
                ('department', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='models_03.department')),
                ('projects', models.ManyToManyField(to='models_03.project')),
            ],
            options={
                'ordering': ('years_of_exp', '-birth_date'),
            },
        ),
    ]
