# Generated by Django 4.1.2 on 2022-11-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_introduction_01', '0002_alter_intro_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
